services:
  postgres:
    image: 'postgres:latest'
    hostname: localhost
    environment:
      - 'POSTGRES_DB=interview'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  data: